name: build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-push:
    name: "Build/Push Image"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.21.5
          - 1.21.13
          - 1.22.7
          - 1.23.1

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Metadata for container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
            type=raw,value=${{ matrix.version }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GORELEASER_VERSION=v${{ matrix.version }}
          push: ${{ if github.event_name == 'push' && github.ref == 'refs/heads/main' }}
